# -*- coding: utf-8 -*-
"""Atividade 03.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18qSWv-W8jEffdOvYVmebKeQW5NkTwCi4

Atividade 03, Marcos Antonio Manfre Ros

Capítulo 4, Tópico Exercícios propostos, páginas 116 a 118, Exercícios 1 ao 14.

1
"""

listanumeros = []
print('Informe os elementos: ')
for i in range(10):
    listanumeros.append(int(input('Elemento ' + str(i+1) + ':\n')))
listanumeros.reverse()
print(listanumeros)

"""2"""

lista1 = []
lista2 = []
print('Lista 1: ')
for i in range (10):
  lista1.append(int(input('Digite o Número ' + str(i+1) + '\n')))
print('-=' * 15)
print('Lista 2:')
for j in range (10):
  lista2.append(int(input('Digite o Número ' + str(j+1) + '\n')))
lista1.extend(lista2)
print('-=' * 15)
print(lista1)

"""6"""

P = int(input('Digite o primeiro termo: '))
R = int(input('Digite a razão da PA: '))
termos = int(input('Digite a quantidade de termos: '))

L = []
cont = 0
while(cont < termos):
    L.append(P)
    P = P + R
    cont+=1
print('a PA é: ',L)

"""10"""

#fiquei com dúvida em como adicionar e mostrar a lista com os números repetidos, gostaria de uma explicação se possivel.

lista = []
while True:
    n = int(input('Digite um número inteiro: '))
    if n in lista:
        print('Número já incluido anteriormente, não será adicionado.')
        lista.remove(n)

    lista += [n]

    flag = str(input('Deseja Continuar? (S/N): ')).strip().lower()[0]
    if flag == 'n':
        print(f'\nOs números digitados foram {sorted(lista)}')
        break

"""12"""

matriz1 = [[0, 0], [0, 0]]
soma1 = 0
for l in range(0,2):
    for c in range(0,2):
        matriz1[l][c] = int(input(f'Digite um valor para a primeira Matriz [{l}, {c}]: '))
for l in range(0, 2):
    for c in range(0, 2):
      print(f'[{matriz1[l][c]:^5}]', end='')
      soma1 += matriz1[l][c]
print()
print(f'A Soma da primeira Matriz é {soma1}')
print('=-=' * 16)

matriz2 = [[0, 0], [0, 0]]
soma2 = 0
for l in range(0,2):
    for c in range(0,2):
        matriz2[l][c] = int(input(f'Digite um valor para a segunda Matriz [{l}, {c}]: '))
for l in range(0, 2):
    for c in range(0, 2):
      print(f'[{matriz2[l][c]:^5}]', end='')
      soma2 += matriz2[l][c]
print()
print(f'A Soma da segunda Matriz é {soma2}')
print('=-=' * 16)
print(f'A Soma final das duas matrizes é {soma1 + soma2}')