# -*- coding: utf-8 -*-
"""Cópia de Atividade 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10lOnKWoy2UXinzxJEig9AiVbzGSqn4bq

Aluno: Marcos Antônio Manfré Rós

Atividade 1

Exércicios do 1 ao 10

1.
"""

x = 0.0
type (x)

y = 18
type (y)

z = x + y
print (z)
type (z)

"""2"""

a = 15
print (A)

"""a letra que recebeu a atribuição foi a minuscula, como a maiuscula não recebeu nada, o programa não encontra a atribuição.

3
"""

A = "Questão 3"
type (A)

B = 25
type (B)

C = 3.9
type (C)

"""4"""

A = 14
B = 5
C = A + B
print (C)

A = 14
B = 5
C = A - B
print (C)

A = 14
B = 5
C = A * B
print (C)

A = 14
B = 5
C = A / B
print (C)

A = 14
B = 5
C = A // B
print (C)

A = 14
B = 5
C = A % B
print (C)

A = 14
B = 5
C = - A
print (C)

A = 14
B = 5
C = A ** B
print (C)

"""5"""

Base = 9
Altura = 6
Calculo_Area = Base * Altura
print (Calculo_Area)

"""6"""

Base = int (input ("Digite a Base do Triangulo: "))
Altura = int (input ("Digite a Altura do Triangulo: "))
Calculo_Area = Base * Altura
print(Calculo_Area)

"""7

"""

valor_hora = float (input ("Digite o valor da hora: "))
hora_trabalhada = int (input ("Digite as horas trabalhadas: "))
qt_hora_extra = int (input ("Digite as horas extras: "))
Hora_extra = (valor_hora * 2) * qt_hora_extra
Salario_horas = valor_hora * hora_trabalhada
Salario_Bruto = Salario_horas + Hora_extra
print ("O Salário bruto do profissional é de: ", end="")
print (Salario_Bruto)

"""8"""

A = 4
B = 5
C = 1
R = (A + B) / 2
print (R)



"""9"""



"""10"""

Qt_ven = int (input ("digite a quantidade vendida: "))
Valor = float (input ("digite o valor unitário: "))
Venda = Qt_ven * Valor
print (Venda)

"""Exércicios do 1 ao 20

1
"""

A = 0
B = -3
print (A > B)

X = 3.7
print (X <= 10.0)

A = 9
B = 16
print (A - B >= 0)

A = 2
B = 4
N = 10
print (A * B < N)

A = 3
B = 9
C = 5
print (10 * A >= B * C)

A = 3
B = 6
C = 5
print (10 * A >= B * C)

N = 7
print (N % 2 == 0)

N = 8
print (N % 2 ==0)

T = "MORANGO"
print (T == "BANANA")

T = "MORANGO"
T > "BANANA"

"""2"""

A = 10
B = 15
C = 4
print (A < B and A < C)

A = 10
B = 15
C = 4
print (A < B or A < C)

A = 1
B = 9
C = 0
print (A >= 0 and B == C)

A = 1
B = 9
C = 9
print (A >= 0 and B == C)

A = 1
B = 9
C = 0
print (A >= 0 or B == C)

A = 1
B = 9
C = 9
print (A >= 0 or B == C)

A = 0
B = 0
C = 0
print (B !=0 and A != C)

A = 0
B = 0
C = 25
print (B != 0 and A != C)

A = 0
B = 0
C = 0
print (B!= 0 or A != C)

A = 0
B = 0
C = 25
print ( B!= 0 or A != C)



"""3"""

A = 10
B = 15
C = 4
print (A < B and A < C or C != 0)

A = 10
B = 15
C = 4
print (A < B and (A < C or C != 0))

A = 1
B = 9
C = 0
print (not (A >= 0 and B == C))

A = 1
B = 9
C = 9
print (not (A >= 0) and not (B == C))

A = 1
B = 9
C = 0
print ((A >= 0 or B == C) and B > A)

A = -2
B = 0
C = 2
print (not (A <= B) or C > B)

A = -2
B = 0
C = 2
print (not (A <= 0) or C > B)

A = 0
B = 1
C = 0
print (A == 0 and B != 0 and C == 0)

A = 5
B = 0
C = 0
print (A == 0 and B != 0 and C == 0)

A = 5
B = 0
C = 0
print (A == 0 or B != 0 or C == 0)

"""4"""

N = int (input("Digite um número: "))
if N >= 0:
  print ("O número digitado é positivo")
else:
  print ("O número digitado é negativo")

"""5"""

N = int (input("Digite um número: "))
resultado = N % 2 
if N == 0:
  print ("O número digitado é par")
else:
  print ("O número digitado é ímpar")

"""6"""

a = int (input("Primeiro número: "))
b = int (input("Segundo número: "))
menor = a
if b < a:
  menor = b
maior = a
if b > a:
  maior = b
print ("o menor valor digitado foi {}".format(menor))
print ("o maior valor digitado foi {}".format(maior))

"""7

"""

r1 = float (input ("Primeiro número: "))
r2 = float (input ("Segundo número: "))
r3 = float (input ("Terceiro número: "))
if r1 < r2 + r3 and r2 < r1 + r3 and r3 < r1 + r2:
  print ("os números acima podem formar um triângulo ", end="")
  if r1 == r2 == r3:
    print ("Equiliátero!")
  elif r1 != r2 != r3 != r1:
    print ("Escaleno!")
  else:
     print ("Isóceles!")
else:
  print ("os números acima não podem formar triângulo")

"""9"""

salario = int (input ("Digite o seu salário mensal: "))
hora_trabalhada = int (input ("Digite as horas trabalhadas: "))
salario_horas = salario / hora_trabalhada
print ("O Salário bruto do profissional é de: ", end="")
print (salario_horas)

"""10"""

print ("Iniciar programa")
Cont = 1
while Cont <= 10:
  print (Cont)
  Cont = Cont + 1
print ("Fim")

"""11"""

num = int (input("Digite um número para a sua tabuada: "))
print ("{} x {:2} = {}".format(num, 1, num*1))
print ("{} x {:2} = {}".format(num, 2, num*2))
print ("{} x {:2} = {}".format(num, 3, num*3))
print ("{} x {:2} = {}".format(num, 4, num*4))
print ("{} x {:2} = {}".format(num, 5, num*5))
print ("{} x {:2} = {}".format(num, 6, num*6))
print ("{} x {:2} = {}".format(num, 7, num*7))
print ("{} x {:2} = {}".format(num, 8, num*8))
print ("{} x {:2} = {}".format(num, 9, num*9))
print ("{} x {:2} = {}".format(num, 10, num*10))






"""13"""

Soma = 0
Qtde = 0
X = 1
while X != 0:
  X = int (input ("Digite X:  "))
  if X != 0:
    Soma = Soma + X
    Qtde = Qtde + 1
print ("Total dos valores digitados = %d" % Soma)
print ("Quantidade de valores = %d" % Qtde)

