# -*- coding: utf-8 -*-
"""Projeto Final.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jBm08KE1Ay62YsYTiTGMAo0V54ZO0awg

"""

# Projeto Final - Sistema para Controle de Estoque
# ALGORITMOS E LINGUAGEM DE PROGRAMAÇÃO | 1º termo


#Funções

def linha(tam=55):
    return '-' * tam

def cabecalho(txt):
    print("")
    print(linha())
    print(txt.center(50))
    print(linha())
    print("")

def mostrarDados():
    mostrar = "------------------------\n\n"
    print("\n------------------------")
    print("Cód.:", listaCodigo[cod])
    print("Nome:", listaNome[cod])
    print("Quantidade:", listaQuantidade[cod])
    print("Valor de custo:", listaCusto[cod])
    print("Valor de venda:", listaVenda[cod])
    return mostrar

def nenhum_produto_cadastrado():
    if listaNome == []:
        nenhumNome = print ("Nenhum produto cadastrado")
    return nenhumNome


#Variáveis


produtoEntrada = 0
produtoSaida = 0
VendaAntiga = 0
lucroObtidoTotal = 0
escolha = 0
cod = 1
menuPrincipal = 0
menuCadastrar = 0
menuControle = 0
quantidadeAntiga = 0

#Listas

listaNome = []
listaCodigo = []
listaQuantidade = []
listaQuantidadeAntiga = []
listaSaida = []
listaEntrada = []
listaCusto = []
listaCustoAntigo = []
listaVenda = []
listaVendaAntiga = []
    

while True:
    cabecalho("SISTEMA DE CONTROLE DE ESTOQUE - SUPERMERCADO PRUDENTÃO")
    menuPrincipal = (input("1. Cadastro de Produtos\n2. Consulta de Produtos\n3. Controle de Estoque\n4. Sair do Programa\n\nDigite uma opção: "))
    print("\n------------------------")

# Menu de cadastro onde existe uma condições para a escolha do menu do usuário

    if(menuPrincipal == "1"):
        while True:
            menuCadastrar = (input("1. Cadastrar produto\n2. Alterar produto\n3. Remover produto\n4. Retornar ao Menu Inicial\n\nDigite uma opção: "))
            print("\n")

            
#Menu para cadastrar um novo produto

            if (menuCadastrar == "1"):
                
                                 
                    while True:
                        print(linha())
                        nomeDigitado = str(input("Digite o Nome do Produto: "))

                        if (nomeDigitado == ""):
                            cabecalho("Nome inválido, tente novamente!")

                        elif (nomeDigitado in listaNome):
                            cabecalho("Nome já cadastrado, tente novamente!")

                        else:                               
                             break                  
                                                                              
                    listaNome.append(nomeDigitado)
                        
                    while True:
                        quantidadeDigitado = int(input("Digite a quantidade do produto: "))

                        if (quantidadeDigitado == ""):
                            cabecalho("Quantidade inválida, tente novamente!")

                        else:
                             break

     
                    listaQuantidade.append(quantidadeDigitado)
                    
                    quantidadeAntiga = quantidadeDigitado
                    listaQuantidadeAntiga.append(quantidadeAntiga)
                      
                    while True:
                        custoDigitado = float(input("Digite o valor de custo do produto: "))

                        if (custoDigitado == ""):
                            cabecalho("Valor inválido!")
                        
                        else:
                              break
                          
                    listaCusto.append(custoDigitado)
                    
                    custoAntigo = custoDigitado
                    listaCustoAntigo.append(custoAntigo)
                    

                    while True:
                        vendaDigitado = float(input("Digite o valor de venda do produto: "))

                        if (vendaDigitado == ""):
                            cabecalho("Valor inválido!")

                        else:
                             break
                          
                    listaVenda.append(vendaDigitado)
                    
                    VendaAntiga = vendaDigitado
                    listaVendaAntiga.append(VendaAntiga)
                    

                    listaCodigo.append((len(listaCodigo)))

                    cabecalho("Produto cadastrado com sucesso!")

                    break

#Menu para alterar um produto
            elif (menuCadastrar == "2"): 
         
                if (listaNome == []):
                    cabecalho("Nenhum produto cadastrado")
                
                else:                    
                    while True:
                        print("Lista de produtos cadastrados")
                        for i in range(len(listaCodigo)):            
                            print(listaCodigo[i]," --- ",listaNome[i])
                        print("\n\n")

                        
                        cod = int(input("Digite o código do produto: "))
                       
                                 
                        if (cod == ""):
                            cabecalho ("Valor inválido,tente novamente!")

                                                    
                        elif (cod not in listaCodigo):
                            cabecalho ("Valor invalido ou produto não cadastrado!")                
                                                   
                        else:
                            print(mostrarDados())
                            print("Deseja alterar os dados exibidos?")
                            escolha = (input("1. Sim\n2. Não\n\nDigite uma opção: "))

                            while True:

#Condição de seguraça para alterar o produto
                                if (escolha == "1"): 

                                    listaNome.pop(cod)                
                                    listaQuantidade.pop(cod)
                                    listaCusto.pop(cod)
                                    listaVenda.pop(cod)
                                    listaCodigo.pop(cod)
                                    
                                    while True:
                                        print(linha())
                                        nomeDigitado = input("Digite o nome do produto: ")

                                        if (nomeDigitado == ""):
                                            cabecalho("Nome inválido, tente novamente!")

                                        elif (nomeDigitado in listaNome):
                                            cabecalho("Nome já cadastrado, tente novamente!")

                                        else:
                                           break
           
                                    listaNome.insert(cod,nomeDigitado)
                                        
                                
                                    while True:
                                        quantidadeDigitado = int(input("Digite a quantidade do produto: "))

                                        if (quantidadeDigitado == ""):
                                            cabecalho("Quantidade inválida, tente novamente!")

                                        else:
                                             break
        
                                    listaQuantidade.insert(cod,quantidadeDigitado)
                                            
                                    quantidadeAntiga = quantidadeDigitado
                                    listaQuantidadeAntiga.insert(cod,quantidadeAntiga)
                      
                                    while True:
                                        custoDigitado = float(input("Digite o valor de custo do produto: "))

                                        if(custoDigitado == ""):
                                            cabecalho("Valor inválido, tente novamente!")
                                        
                                        else:
                                              break
     
                                    listaCusto.insert(cod,custoDigitado)
                                    
                                    custoAntigo = custoDigitado
                                    listaCustoAntigo.insert(cod,custoAntigo)
                                    

                                    while True:
                                        vendaDigitado = float(input("Digite o valor de venda do produto: "))

                                        if(vendaDigitado == ""):
                                            cabecalho("Valor inválido, tente novamente!")

                                        else:
                                              break
                                                 
                                    listaVenda.insert(cod,vendaDigitado)
                                    
                                    VendaAntiga = vendaDigitado
                                    listaVendaAntiga.insert(cod, VendaAntiga)
                                    

                                    listaCodigo.insert(cod,cod)


                                    cabecalho("Produto alterado com sucesso!")

                                    break
                                break
                            break

#Remover produto cadastrado
            elif (menuCadastrar == "3"):

                if (listaNome == []):
                    cabecalho("Nenhum produto cadastrado")

                else:
                    while True:

                        print("Lista de produtos cadastrados")
                        for i in range(len(listaCodigo)):            
                            print(listaCodigo[i]," --- ",listaNome[i])
                        print("\n\n")
                    
                        cod = int(input("Digite o código do produto: "))

                        if cod not in listaCodigo:
                            cabecalho("Valor invalido ou produto não cadastrado")                        
                        
                        else:
                            print(mostrarDados())
                            print("Deseja excluir os dados exibidos?")
                            escolha = (input("1. Sim\n2. Não\n\nDigite uma opção: "))

                          
                            if(escolha == "1"):

                                listaNome.pop(cod)                
                                listaQuantidade.pop(cod)
                                listaCusto.pop(cod)
                                listaVenda.pop(cod)
                                listaCodigo.pop(cod)
                                

                                cabecalho("Produto excluido com sucesso!")
                                break

                            elif(escolha == "2"):
                                print(linha)
                                break

                            elif(escolha == ""):
                                cabecalho("Valor invalido ou produto não cadastrado")

                            else:
                                cabecalho("Valor invalido ou produto não cadastrado")
                    break
                
                            
#Retornar ao menu principal
            elif (menuCadastrar == "4"):
                menuCadastrar = 0
                break

            else:
                cabecalho("O número ou caracter digitado é inválido.\nPor favor, tente novamente")
            

# Consultar um produto    
    elif(menuPrincipal == "2"):
        while True:
            if (listaNome == []):
                cabecalho("Nenhum produto cadastrado")
                    
            else:
                while True:
                    
                    print("Lista de produtos cadastrados")
                    for i in range(len(listaCodigo)):            
                        print(listaCodigo[i]," --- ",listaNome[i])
                    print("\n\n")

                    cod = int(input("Digite o código do produto: "))

                    if (cod not in listaCodigo):
                        cabecalho("Valor invalido ou produto não cadastrado")

                    else:
                        
                        print(mostrarDados())
                    break
                        
            break


#Controlar estoque
    elif(menuPrincipal == "3"):
        while True:
            print(linha())
            menuControle = input("1. Registrar entrada de produtos\n2. Registrar saída de produtos\n3. Saldo de estoque unitário\n4. Total de estoque\n5. Voltar ao menu principal\n\nDigite uma opção: ")

#Registrar entrada de produtos
            if (menuControle == "1"):
                if (listaNome == []):
                    cabecalho("Nenhum produto cadastrado")

                else:
                    while True:

                        print("Lista de produtos cadastrados")
                        for i in range(len(listaCodigo)):            
                            print(listaCodigo[i]," --- ",listaNome[i])
                        print("\n\n")
                    
                        cod = int(input("Digite o código do produto: "))

                        if cod not in listaCodigo:
                            cabecalho("Valor invalido ou produto não cadastrado")                     
                        
                        else:
                            print(mostrarDados())
                            print("Deseja alterar a quantidade de produto exibido?")
                            escolha = (input("1. Sim\n2. Não\n\nDigite uma opção: "))

                           
                            if(escolha == "1"):
                                           
                                quantidade_adicionada = int(input("Digite a quantidade que deseja registrar: "))
                                quantidade_nova = int(listaQuantidade[cod]) + quantidade_adicionada
                                
                                listaQuantidade.pop(cod)
                                listaQuantidade.insert(cod, quantidade_nova)

                                produtoEntrada += quantidade_adicionada 
                                listaEntrada.insert(cod, produtoEntrada)

                                
                                cabecalho("Quantidade registrada com sucesso!")
                                break

                            elif(escolha == "2"):
                                print("-----------------------------\n")
                                break

                            elif(escolha == ""):
                                cabecalho("Valor invalido ou produto não cadastrado")                               

                            else:
                                cabecalho("Valor invalido ou produto não cadastrado")
                    break
        
# Registrar saída de produtos

            elif (menuControle == "2"):
                if (listaNome == []):
                    cabecalho("Nenhum produto cadastrado")

                else:
                    while True:

                        print("Lista de produtos cadastrados")
                        for i in range(len(listaCodigo)):            
                            print(listaCodigo[i]," --- ",listaNome[i])
                        print("\n\n")
                    
                        cod = int(input("Digite o código do produto: "))

                        if cod not in listaCodigo:
                            cabecalho("Valor invalido ou produto não cadastrado")                       
                        
                        else:
                            print(mostrarDados())
                            print("Deseja alterar a quantidade de produto exibido?")
                            escolha = (input("1. Sim\n2. Não\n\nDigite uma opção: "))

                            

                            if(escolha == "1"):

                                print("\n---------------------------------------")
                                quantidade_removida = int(input("Digite a quantidade que deseja remover: "))
                                      
                                quantidade_nova = int(listaQuantidade[cod]) - quantidade_removida
                                
                                listaQuantidade.pop(cod)
                                listaQuantidade.insert(cod, quantidade_nova)

                                produtoSaida += quantidade_removida 
                                listaSaida.insert(cod, produtoSaida)

                                                                
                                if(escolha == "1"):
                                    cabecalho("Baixa de produto concluida com sucesso!")
                                    break

                            elif(escolha == "2"):
                                print("-----------------------------\n")
                                break

                            elif(escolha == ""):
                                cabecalho("Valor invalido ou produto não cadastrado")                             

                            else:
                                cabecalho ("Valor invalido ou produto não cadastrado")
                    break
#Saldo de estoque unitário
            elif (menuControle == "3"):
                if (listaNome == []):
                    cabecalho("Nenhum produto cadastrado")

                else:
                    while True:

                        print("Lista de produtos cadastrados")
                        for i in range(len(listaCodigo)):            
                            print(listaCodigo[i]," --- ",listaNome[i])
                        print("\n\n")
                    
                        cod = int(input("Digite o código do produto: "))

                        if cod not in listaCodigo:
                            cabecalho("Valor invalido ou produto não cadastrado")                      
                        
                        else:
                                                      
                            print("\n------------------------")
                            print("Código.:", listaCodigo[cod])
                            print("Nome:", listaNome[cod])
                            print("Quantidade inicial: ", listaQuantidadeAntiga[cod])
                            print("Quantidade atual: ", listaQuantidade[cod])
                            print("------------------------\n")
                            
                                                         
                            break                        
                    
#Análise total de estoque
            elif (menuControle == "4"):

                if (listaNome == []):
                    cabecalho("Nenhum produto cadastrado")

                else:
                    print("\n-------------------------------------")
                    print("Lista de produtos cadastrados")
                    for i in range(len(listaCodigo)):            
                        print(listaCodigo[i]," --- ",listaNome[i], " - Quantidade disponível: ",listaQuantidade[i])
                    print("-------------------------------------\n")
                           

#Retornar ao menu principal
            elif(menuControle == "5"):
                break

            else:
                cabecalho("O número ou caracter digitado é inválido.\nPor favor, tente novamente.")
    
    elif(menuPrincipal == "4"):
        print("Obrigado por utilizar o nosso programa, estamos tentando melhorar sempre! ")
        break

    else:
        cabecalho("O número ou caracter digitado é inválido.\nPor favor, tente novamente.")